// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCluwZ2h_w_Nul_Acgw8Nhfc1IxS7DVI',
    appId: '1:133346483325:web:794050fc7e33e0b2472514',
    messagingSenderId: '133346483325',
    projectId: 'motor-shop-manager',
    authDomain: 'motor-shop-manager.firebaseapp.com',
    storageBucket: 'motor-shop-manager.firebasestorage.app',
    measurementId: 'G-0VP2F8E76X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1s4Ac1tew6zBe9cSBqin5-XOWK1bqks',
    appId: '1:133346483325:android:5e646ada873a5f5e472514',
    messagingSenderId: '133346483325',
    projectId: 'motor-shop-manager',
    storageBucket: 'motor-shop-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWqrMhg2vGk2Sxm1bPiuokruo5VOp4oY',
    appId: '1:133346483325:ios:c86df5454ae53134472514',
    messagingSenderId: '133346483325',
    projectId: 'motor-shop-manager',
    storageBucket: 'motor-shop-manager.firebasestorage.app',
    iosBundleId: 'com.example.motorshop',
  );

}